name: Build and Deploy to Azure

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  IMAGE_NAME: flexi-portal

permissions:
  id-token: write 
  contents: read 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: c69b36ac-dd24-451a-85e2-45cb75a29c38
        auth-type: oidc 

    - name: ACR Login
      run: az acr login --name ${{ secrets.ACR_NAME }}

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} .

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        images: ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
